# Site settings
title: "Craig Cooper Resume"
description: "A resume template for Craig Cooper made with Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Craig Cooper"
resume_title:                   "Sofware Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "craigcooper87911@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Software developer with over 7 years of experience with full stack development. Knowledge of JavaScript, Jquery, cURL, API's, PHP, Unix, CSS, HTML, Node.js, Angular, Git, GitHub, Travis CI, Unit Testing.</p>"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/craigcooper11"
  resume_linkedin_url:          "https://www.linkedin.com/in/craig-c-51b405146/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
